/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as FinancialPlannerRouteImport } from './routes/financial-planner'
import { Route as InvestmentCalculatorRouteImport } from './routes/investment-calculator'
import { Route as LoanCalculatorRouteImport } from './routes/loan-calculator'
import { Route as PercentageCalculatorRouteImport } from './routes/percentage-calculator'
import { Route as SipCalculatorRouteImport } from './routes/sip-calculator'
import { Route as TipCalculatorRouteImport } from './routes/tip-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialPlannerRoute = FinancialPlannerRouteImport.update({
  id: '/financial-planner',
  path: '/financial-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentCalculatorRoute = InvestmentCalculatorRouteImport.update({
  id: '/investment-calculator',
  path: '/investment-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCalculatorRoute = LoanCalculatorRouteImport.update({
  id: '/loan-calculator',
  path: '/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentageCalculatorRoute = PercentageCalculatorRouteImport.update({
  id: '/percentage-calculator',
  path: '/percentage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SipCalculatorRoute = SipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TipCalculatorRoute = TipCalculatorRouteImport.update({
  id: '/tip-calculator',
  path: '/tip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/financial-planner': typeof FinancialPlannerRoute
  '/investment-calculator': typeof InvestmentCalculatorRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/tip-calculator': typeof TipCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/financial-planner': typeof FinancialPlannerRoute
  '/investment-calculator': typeof InvestmentCalculatorRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/tip-calculator': typeof TipCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/financial-planner': typeof FinancialPlannerRoute
  '/investment-calculator': typeof InvestmentCalculatorRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/percentage-calculator': typeof PercentageCalculatorRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/tip-calculator': typeof TipCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/financial-planner'
    | '/investment-calculator'
    | '/loan-calculator'
    | '/percentage-calculator'
    | '/sip-calculator'
    | '/tip-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/financial-planner'
    | '/investment-calculator'
    | '/loan-calculator'
    | '/percentage-calculator'
    | '/sip-calculator'
    | '/tip-calculator'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/financial-planner'
    | '/investment-calculator'
    | '/loan-calculator'
    | '/percentage-calculator'
    | '/sip-calculator'
    | '/tip-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  FinancialPlannerRoute: typeof FinancialPlannerRoute
  InvestmentCalculatorRoute: typeof InvestmentCalculatorRoute
  LoanCalculatorRoute: typeof LoanCalculatorRoute
  PercentageCalculatorRoute: typeof PercentageCalculatorRoute
  SipCalculatorRoute: typeof SipCalculatorRoute
  TipCalculatorRoute: typeof TipCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-planner': {
      id: '/financial-planner'
      path: '/financial-planner'
      fullPath: '/financial-planner'
      preLoaderRoute: typeof FinancialPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-calculator': {
      id: '/investment-calculator'
      path: '/investment-calculator'
      fullPath: '/investment-calculator'
      preLoaderRoute: typeof InvestmentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-calculator': {
      id: '/loan-calculator'
      path: '/loan-calculator'
      fullPath: '/loan-calculator'
      preLoaderRoute: typeof LoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentage-calculator': {
      id: '/percentage-calculator'
      path: '/percentage-calculator'
      fullPath: '/percentage-calculator'
      preLoaderRoute: typeof PercentageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip-calculator': {
      id: '/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/sip-calculator'
      preLoaderRoute: typeof SipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tip-calculator': {
      id: '/tip-calculator'
      path: '/tip-calculator'
      fullPath: '/tip-calculator'
      preLoaderRoute: typeof TipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  FinancialPlannerRoute: FinancialPlannerRoute,
  InvestmentCalculatorRoute: InvestmentCalculatorRoute,
  LoanCalculatorRoute: LoanCalculatorRoute,
  PercentageCalculatorRoute: PercentageCalculatorRoute,
  SipCalculatorRoute: SipCalculatorRoute,
  TipCalculatorRoute: TipCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
